<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Add Foto_bi bi-pencil-fill fs-7</name>
   <tag></tag>
   <elementGuidId>4113a405-2087-443f-9d01-eaedf4abcbab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-pencil-fill.fs-7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_contacts_main']/div[2]/form/div/div/div/label/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a1fea735-eeb5-4fc4-a109-11a2abb80111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-pencil-fill fs-7</value>
      <webElementGuid>1c206640-f872-4075-9419-018f4d183b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_contacts_main&quot;)/div[@class=&quot;card-body pt-5&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mb-7&quot;]/div[@class=&quot;mt-1&quot;]/div[@class=&quot;image-input image-input-outline&quot;]/label[@class=&quot;btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow&quot;]/i[@class=&quot;bi bi-pencil-fill fs-7&quot;]</value>
      <webElementGuid>bf4e2353-e009-44e5-80c2-fc763ad5ec2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div[2]/form/div/div/div/label/i</value>
      <webElementGuid>7fd44b11-af3c-469b-aeb4-3370191d47b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label/i</value>
      <webElementGuid>8ffe7c36-15ca-43c2-8036-fcc343084ba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
