<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_bi bi-eye-slash fs-2 (1)</name>
   <tag></tag>
   <elementGuidId>5c8fb31c-33f1-43a4-8eb1-51492b4a326a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_contacts_main']/div[2]/form/div[4]/div/div/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-eye-slash.fs-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e36544e7-32ae-4a41-8338-614d9015fb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-eye-slash fs-2</value>
      <webElementGuid>51819497-f0d2-49c0-b3ca-ba6399153cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_contacts_main&quot;)/div[@class=&quot;card-body pt-5&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mb-10 fv-row&quot;]/div[@class=&quot;mb-1&quot;]/div[@class=&quot;position-relative mb-3 focus-input&quot;]/span[@class=&quot;btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2&quot;]/i[@class=&quot;bi bi-eye-slash fs-2&quot;]</value>
      <webElementGuid>b1fc22ba-b76f-4dda-b15f-117c0e37038c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div[2]/form/div[4]/div/div/span/i</value>
      <webElementGuid>d4040f97-723d-4aa8-8086-c854ad31da59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span/i</value>
      <webElementGuid>f4cc2d9d-f396-4df4-a919-0a03f69e6a2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
