<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_NOTE</name>
   <tag></tag>
   <elementGuidId>5d7711db-408c-4876-82e3-69ff757ff835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content_container']/div[2]/table/tbody/tr[4]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>79095d62-7f4f-434e-9ef4-f57b18ebec53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> NOTE :</value>
      <webElementGuid>0a2bb8ba-06bc-4c7c-9841-e8980861ab0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content_container&quot;)/div[@class=&quot;col-lg-12&quot;]/table[@class=&quot;table align-middle table-row-dashed fs-6 gy-5&quot;]/tbody[1]/tr[4]/td[1]</value>
      <webElementGuid>92f1a226-d23e-477c-823d-6e2b589a997f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content_container']/div[2]/table/tbody/tr[4]/td</value>
      <webElementGuid>08d1495e-b0d0-40a7-b7bc-7b627801e08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATE :'])[1]/following::td[2]</value>
      <webElementGuid>97ec078c-d6e5-429e-81b5-da6fcffc3982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TITLE :'])[1]/following::td[4]</value>
      <webElementGuid>fe4de9e5-6084-4393-b403-afdb1d4ca88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tes'])[1]/preceding::td[1]</value>
      <webElementGuid>c837b88a-8556-4237-bcae-a647cd46675b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STATUS :'])[1]/preceding::td[2]</value>
      <webElementGuid>028eb7a0-928f-4e3b-b76f-fc6faf34be18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NOTE :']/parent::*</value>
      <webElementGuid>fb8f0dab-9f67-4278-b6c1-c387ea883564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[4]/td</value>
      <webElementGuid>e7020e26-e669-445c-b3dd-6cccd6c7e639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' NOTE :' or . = ' NOTE :')]</value>
      <webElementGuid>6b49b9a9-2e4d-424c-9338-b5869e249d52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
