<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sumber Data</name>
   <tag></tag>
   <elementGuidId>0dd708a5-0929-406d-93fc-301f52552bfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-filter-09-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-filter-09-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b4f5037-501b-454b-9d13-5df1a468db7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>8f75ea0c-190f-4cd7-9281-a953eb3d13ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-filter-09-container</value>
      <webElementGuid>ce583f59-b557-4b90-9ad4-0c296582bbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>001d66d0-5871-4667-b5b2-3de21c0baf73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eca9b572-4fff-474f-aec1-2da1d071da8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sumber Data</value>
      <webElementGuid>2780e8b7-cbeb-4c37-b285-d4204d79d6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sumber Data</value>
      <webElementGuid>20fcd96e-7200-4252-b5d6-1dab0b66c498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-filter-09-container&quot;)</value>
      <webElementGuid>cab12c5b-b1c0-4496-9edf-134985fc5aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-filter-09-container']</value>
      <webElementGuid>6c5942c5-a3da-4c3e-974a-1bf82b746395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content_container']/div/div/div[2]/div/div/form/div/div/span/span/span/span</value>
      <webElementGuid>85d60953-9ade-4185-8593-b03326ac79ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berdasarkan'])[1]/following::span[4]</value>
      <webElementGuid>c26f284f-1192-4bbd-a0f7-5acf34f8c814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::span[4]</value>
      <webElementGuid>99d694cc-ce1d-4ccd-9431-78a637efc7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih'])[1]/preceding::span[3]</value>
      <webElementGuid>b1272bdd-188e-4cb1-86b3-214e34dd4612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select option'])[1]/preceding::span[3]</value>
      <webElementGuid>b945c608-05ff-4d05-a232-8e372397ea9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>daedcce2-18be-4b97-a379-5149e1903842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-filter-09-container' and @title = 'Sumber Data' and (text() = 'Sumber Data' or . = 'Sumber Data')]</value>
      <webElementGuid>2ea056ca-3e0e-45e3-8027-d9bb9b71583d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
