<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Funding_potential_category</name>
   <tag></tag>
   <elementGuidId>c3c49483-c400-4f6f-ba5e-3777b1df1422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='category_product_count_yes'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1889bca8-bfb5-4a36-99bf-074a40092331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>8e117e1b-644d-49b8-86f6-bb0d0cf908a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>71e720e8-b1e6-4da5-b0bd-b10e60ec237f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>tidak_perlu</value>
      <webElementGuid>d7ce14df-261d-4cd5-ab76-09fb63d18107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>potential_category</value>
      <webElementGuid>2528be51-ff31-484c-9879-265ab001fc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category_product_count_yes</value>
      <webElementGuid>3401c253-8829-4a3a-8a4a-9f2a76049e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/div[@class=&quot;col-xl-12&quot;]/div[@id=&quot;kt_contacts_main&quot;]/div[@class=&quot;card-body pt-5&quot;]/div[@class=&quot;row fv-row mb-7&quot;]/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;d-flex mt-1&quot;]/div[@class=&quot;form-check form-check-custom form-check-solid me-5&quot;]/input[@id=&quot;category_product_count_yes&quot;]</value>
      <webElementGuid>67afb3fd-dd9a-49c3-98f7-d3cb5f5f01a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='category_product_count_yes'])[3]</value>
      <webElementGuid>07d836b1-2c35-4532-866f-5f6a03bdd84c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div/div[2]/div[2]/div/div[3]/input</value>
      <webElementGuid>8239e258-5f0d-4452-b7f1-a81302203cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>619f0083-358c-4083-8c73-f5f2f867242f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'potential_category' and @id = 'category_product_count_yes']</value>
      <webElementGuid>3665ce6a-482f-4e14-9791-64fefd36a71e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
