<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Masuk</name>
   <tag></tag>
   <elementGuidId>84d01fe8-7e59-4755-94f4-d67fc10b1ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.indicator-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kt_sign_in_submit']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8435bedf-e64c-4fd1-b572-58ef0d8a7882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>indicator-label</value>
      <webElementGuid>d9283a9b-b7d9-43e2-b244-f7ae428e4d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>129e9961-debc-4f33-b3ba-c0a90156464c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_sign_in_submit&quot;)/span[@class=&quot;indicator-label&quot;]</value>
      <webElementGuid>3513bcc8-dd05-40ee-930d-d401a3b67bc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='kt_sign_in_submit']/span</value>
      <webElementGuid>a58cde5b-9f17-4361-9d82-76a86f2e62ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::span[2]</value>
      <webElementGuid>64d81f82-3963-40e4-a1c5-b6032482b290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::span[2]</value>
      <webElementGuid>a5bbd317-292e-4e8f-8ab1-4cc0ebecd2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohon tunggu...'])[1]/preceding::span[1]</value>
      <webElementGuid>5c7e2b13-15e8-4ba3-84b2-9e930550fcc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'kt_sign_in_submit', '&quot;', ')/span[@class=', '&quot;', 'indicator-label', '&quot;', ']')])[1]/preceding::span[3]</value>
      <webElementGuid>4c062ec1-59ce-4ee8-86d3-d86103318156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>223b4df4-edd4-444f-835c-5cf50fce7aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>e8df1591-3cb8-4387-829f-3aad6fd290d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>457bff5b-5ea8-47aa-b1bd-3cb2b426a9ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
