<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_bi bi-eye-slash fs-2 (1)</name>
   <tag></tag>
   <elementGuidId>4b7a356f-b69e-48f2-9118-d4e1a49df4c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_contacts_main']/div[2]/form/div[4]/div/div/div/div/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-eye-slash.fs-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6bbf5ce8-4ce8-44dd-bae5-d97112faa162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-eye-slash fs-2</value>
      <webElementGuid>26e41662-d22a-48fb-94d1-8e2012c6527c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_contacts_main&quot;)/div[@class=&quot;card-body pt-5&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;row row-cols-1 row-cols-sm-2 rol-cols-md-1 row-cols-lg-2&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;mb-10 fv-row&quot;]/div[@class=&quot;mb-1&quot;]/div[@class=&quot;position-relative mb-3 focus-input&quot;]/span[@class=&quot;btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2&quot;]/i[@class=&quot;bi bi-eye-slash fs-2&quot;]</value>
      <webElementGuid>b4f44c6c-c20f-443f-a073-662fbfedd6cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div[2]/form/div[4]/div/div/div/div/span/i</value>
      <webElementGuid>1be304d6-2c6c-499d-97c6-ac82f57ed741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/span/i</value>
      <webElementGuid>144e6f57-cf11-4f71-b678-c97f2d33a385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
