<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Warm</name>
   <tag></tag>
   <elementGuidId>cceb976b-53b4-475b-a115-1f5ab08c553f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content_container']/div/div[3]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c276907-5260-4f1b-8d5a-0642fda5b75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://frontliner.intermediatech.id/layanan/assignment_index?type=warm</value>
      <webElementGuid>b8672dc5-1c78-4b0f-a3bb-de02b886bb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white fw-bold </value>
      <webElementGuid>c16dec92-82a7-4b71-9e47-28ddf645da90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Warm</value>
      <webElementGuid>7e6d3dd3-f9d1-46a3-ba80-db34043a8edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content_container&quot;)/div[@class=&quot;row gy-5 g-xl-8&quot;]/div[@class=&quot;col bg-warning px-6 py-8 rounded-2 me-3 mb-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-7&quot;]/a[@class=&quot;text-white fw-bold&quot;]</value>
      <webElementGuid>bae30a92-3917-4619-b964-d45afb9f0d70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content_container']/div/div[3]/div/div/a</value>
      <webElementGuid>3d026f7c-5d66-4cda-a8f2-2f418994ae81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Warm')]</value>
      <webElementGuid>5dbec65a-3256-47d8-8eb3-f93a8103fdda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOT'])[1]/following::a[1]</value>
      <webElementGuid>188b5beb-e451-405a-b4bf-ef6ce9d4cf2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment'])[2]/following::a[2]</value>
      <webElementGuid>9ffc51de-58da-463f-924a-864be237636e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cold'])[1]/preceding::a[1]</value>
      <webElementGuid>45c691bc-e1ce-4c41-9fb4-5dbc633c6551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Closed'])[1]/preceding::a[2]</value>
      <webElementGuid>925bdfee-5bb0-48bf-8e16-f7d26b70aeb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Warm']/parent::*</value>
      <webElementGuid>22e76c9b-b93b-4717-9cb8-ad7193859145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://frontliner.intermediatech.id/layanan/assignment_index?type=warm')]</value>
      <webElementGuid>fd98ad4f-e986-4d02-b8fa-cedb8e40eacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/a</value>
      <webElementGuid>fd8e4eec-267f-4807-8e86-aa93dd3c1ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://frontliner.intermediatech.id/layanan/assignment_index?type=warm' and (text() = 'Warm' or . = 'Warm')]</value>
      <webElementGuid>8d82114e-0951-4ded-be85-264fb3f2f592</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
