<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Marketing Pembiayaan -                _9d6040</name>
   <tag></tag>
   <elementGuidId>4269f205-5568-4bb0-a849-60d100246c9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-marketing_id-hq-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-marketing_id-hq-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cdb4e483-1af7-415c-9eef-ed9093239e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>6a07989b-da7b-4dd2-a859-29d8a6688740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-marketing_id-hq-container</value>
      <webElementGuid>054c2c89-6770-4e88-af64-a441d662c7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a31d305f-b393-45c2-90a5-bb5e85b795cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06d3bed2-344b-419a-9d14-be95c0e776ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marketing Pembiayaan -
                                            financing</value>
      <webElementGuid>e98071bc-7e0e-4360-9ff1-c7e12f4e0c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marketing Pembiayaan -
                                            financing</value>
      <webElementGuid>977a2a28-244d-42d8-a84b-bf60f887023b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-marketing_id-hq-container&quot;)</value>
      <webElementGuid>0891a7da-e87e-41eb-bd13-12ec5c4c3614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-marketing_id-hq-container']</value>
      <webElementGuid>670ec4d5-7dbb-466f-a28f-58afb7ae7f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div/form/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>6d32c2e5-5f1b-484f-8b1b-b49806807fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing'])[1]/following::span[4]</value>
      <webElementGuid>c4edd177-cb9a-4bc3-ac9d-bb65eb1bdb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nasabah'])[1]/preceding::span[3]</value>
      <webElementGuid>c3fb3df7-39d8-426a-b197-f3b509195bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>a28d526d-6d1a-43b1-83b8-96fa73ec07fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-marketing_id-hq-container' and @title = 'Marketing Pembiayaan -
                                            financing' and (text() = 'Marketing Pembiayaan -
                                            financing' or . = 'Marketing Pembiayaan -
                                            financing')]</value>
      <webElementGuid>d63c2433-00a6-444d-a1d1-c8b19ec6fb94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
