<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Jacob Langdon - personal - nasabah_1</name>
   <tag></tag>
   <elementGuidId>dbb176d1-c36b-4974-aa9e-eb8b15835d9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-customer_id-if-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-customer_id-if-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>378797e5-75e0-4311-82ae-24a07289ee53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>40bfe0f6-87a6-46a9-8495-662ef4f547a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-customer_id-if-container</value>
      <webElementGuid>17be3aca-8e3e-410a-be86-7e99dc3da306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1a23184f-85e1-48fa-98a6-da786394acd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e6a1b600-9375-44ab-94c5-4da5bbe989d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>
                                            Jacob Langdon - personal - nasabah</value>
      <webElementGuid>c6f868b4-e57b-4477-b01b-2aef7ad1ebd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Jacob Langdon - personal - nasabah</value>
      <webElementGuid>27cab64c-0ede-40c8-b1c3-69939f67fe11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-customer_id-if-container&quot;)</value>
      <webElementGuid>59552826-9981-4844-9000-d595dca32159</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-customer_id-if-container']</value>
      <webElementGuid>b3e3ffda-1b13-4449-93ad-4f31fc65606e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div/form/div[2]/div[2]/div/span/span/span/span</value>
      <webElementGuid>af3e6af2-6e9c-44a4-a633-1e96c8db536b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nasabah'])[1]/following::span[4]</value>
      <webElementGuid>b5378915-9788-4e7f-bbb0-9c0410b94457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::span[3]</value>
      <webElementGuid>a8816145-c6f4-4337-807b-eb9d269b289c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please wait...'])[1]/preceding::span[4]</value>
      <webElementGuid>dc754e77-59dd-4d48-9258-512314f1d34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span/span/span/span</value>
      <webElementGuid>32681b07-c55d-4c51-80c3-16cf251ef2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-customer_id-if-container' and @title = '
                                            Jacob Langdon - personal - nasabah' and (text() = '
                                            Jacob Langdon - personal - nasabah' or . = '
                                            Jacob Langdon - personal - nasabah')]</value>
      <webElementGuid>5dc4fa08-1b83-457c-b782-63633bf43f7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
