<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Marketing2P -                         _5893f9</name>
   <tag></tag>
   <elementGuidId>b4117715-e68b-4766-aec8-1ea195b6053a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-marketing_id-vi-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-marketing_id-vi-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e917a75c-2e88-4c86-a54b-c46a44eb0afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>4d6046dc-bbdd-49e0-884e-12038a2c683b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-marketing_id-vi-container</value>
      <webElementGuid>a2938fe7-4a9a-418a-846b-3767c3dda2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>6878bf74-094a-4943-b422-1031828aecbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>de22af02-f8c5-4404-99f4-713c05e68a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marketing2P -
                                            financing</value>
      <webElementGuid>6e11db28-173e-4975-8ca3-9a3bd624699f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marketing2P -
                                            financing</value>
      <webElementGuid>cc00fd19-6cfb-4ec1-a299-b0f8a5d3d230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-marketing_id-vi-container&quot;)</value>
      <webElementGuid>4223942b-897f-4bd8-a9b3-6bd1b79ad3d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-marketing_id-vi-container']</value>
      <webElementGuid>e782c6e4-447d-4b37-a439-50fca1ca44e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div/form/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>df0dfc77-bd91-4412-8c75-3d01979e631d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing'])[1]/following::span[4]</value>
      <webElementGuid>02aac464-63ad-402a-afd7-232b79e19b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nasabah'])[1]/preceding::span[3]</value>
      <webElementGuid>1f63cae3-10c3-4543-9081-ee24cdc001e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>79754c11-cbf4-4fd2-8a14-9ff039677381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-marketing_id-vi-container' and @title = 'Marketing2P -
                                            financing' and (text() = 'Marketing2P -
                                            financing' or . = 'Marketing2P -
                                            financing')]</value>
      <webElementGuid>e13e25b2-dc52-4d00-8206-83db5fb4bed9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
