<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Marketing2P -                         _5893f9_1</name>
   <tag></tag>
   <elementGuidId>ef257a9f-7f5c-4748-8bc7-e183b5fa35b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-marketing_id-su-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-marketing_id-su-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>857a0a15-44e0-479d-b019-27d9bf3c5cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>5def3061-98b6-4d01-80ff-df5963509fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-marketing_id-su-container</value>
      <webElementGuid>7f59b781-7914-42c7-a802-97bff4fa9b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4a96b24d-2eb0-468f-85a5-e49ed09174ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5a716f5d-0543-4694-8262-c52516b55cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marketing2P -
                                            financing</value>
      <webElementGuid>42fae20e-da3a-4190-a7a3-5d3c5c315df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marketing2P -
                                            financing</value>
      <webElementGuid>9e3d2ce3-f9a1-4615-b3ca-7347a68accde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-marketing_id-su-container&quot;)</value>
      <webElementGuid>ebae17e1-478b-428b-b983-1b88037ec5b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-marketing_id-su-container']</value>
      <webElementGuid>1155b06a-fa10-42d5-834b-e43829b2a3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div/form/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>1de4fb3f-9599-46e1-bf59-da33734eb5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing'])[1]/following::span[4]</value>
      <webElementGuid>7b1007bb-c68a-4f09-a811-d9345b2d4a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nasabah'])[1]/preceding::span[3]</value>
      <webElementGuid>57de83c8-fb46-471e-9294-cc9d68792398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>b397b6a9-d809-446c-a85c-57653d8d2990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-marketing_id-su-container' and @title = 'Marketing2P -
                                            financing' and (text() = 'Marketing2P -
                                            financing' or . = 'Marketing2P -
                                            financing')]</value>
      <webElementGuid>547525bb-2e46-4011-9302-d5968895dcb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
