<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>e1988b0c-1ad6-412a-965a-8c05876669b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-12.col-md-7.d-flex.align-items-center.justify-content-center.justify-content-md-end</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_table_users_wrapper']/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10016406-212d-4b1e-8da9-14e749d59977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end</value>
      <webElementGuid>324f1ec8-9ab5-4b5e-bca1-e0464e1ebda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2d2476fd-addf-4a79-8863-ad60e65d240a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_table_users_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end&quot;]</value>
      <webElementGuid>9c0d1cec-dd7b-4cec-b9cb-28cb3934268c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_table_users_wrapper']/div[2]/div[2]</value>
      <webElementGuid>440a63db-e58f-4933-b053-a1d243ad5455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funding'])[2]/following::div[4]</value>
      <webElementGuid>5d2f85b0-47c4-4e36-8ecc-503bcaf16a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nasabah'])[4]/following::div[4]</value>
      <webElementGuid>1dc78a6b-e895-4367-a30e-e82f68423a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intermedia Technology Corporation'])[1]/preceding::div[2]</value>
      <webElementGuid>782a377c-edc7-45c7-8008-5243694901eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>bd9b04c3-e826-4373-a82d-14dd2b243fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1' or . = '1')]</value>
      <webElementGuid>d98ab0ae-a95d-46fc-a240-1cf3946aa006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
