<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Jabatan                       _665c11</name>
   <tag></tag>
   <elementGuidId>3ddefb64-d826-444b-be10-4bc1b72c4461</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jabatan_value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jabatan_value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>83d46221-60d3-4d17-82f8-1287ad31e453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b7672fe5-aae7-4c59-8fa4-4c248d37ad22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jabatan_value</value>
      <webElementGuid>2fe83341-4d79-4bad-bb3a-b03db97948a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-select-solid</value>
      <webElementGuid>a8c40bbb-a24b-47fc-9560-b91dc2c73465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>position</value>
      <webElementGuid>79d79c58-6e58-4b1d-ad25-8e0fcfe0d290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kt-ecommerce-settings-type</name>
      <type>Main</type>
      <value>select2_flags</value>
      <webElementGuid>5fe05779-86e4-4660-999b-00d9555d2486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Jabatan</value>
      <webElementGuid>190404f2-375f-4905-ac25-e4126ca34690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Pilih Jabatan
                                Komisaris
                                Direktur
                                Staff
                            </value>
      <webElementGuid>90f014c8-bd4b-4617-962b-6fcb728758e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jabatan_value&quot;)</value>
      <webElementGuid>c432c9ce-9a5f-4753-882f-6005c429eca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jabatan_value']</value>
      <webElementGuid>aecdcb81-3e07-4496-b410-b8109c07a0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jabatan']/div[2]/select</value>
      <webElementGuid>b9da7abf-6495-40c5-980d-454457c14ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jabatan'])[1]/following::select[1]</value>
      <webElementGuid>6c9cad1a-d9ec-4d4f-b700-eb2b3ab58f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendapatan Per Bulan'])[1]/preceding::select[1]</value>
      <webElementGuid>0516d7b5-c5fb-4e98-91a8-f32e41a222b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/select</value>
      <webElementGuid>937f9962-5c48-4abb-ab4f-9e8f7f1806e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'jabatan_value' and @name = 'position' and @placeholder = 'Pilih Jabatan' and (text() = '
                                Pilih Jabatan
                                Komisaris
                                Direktur
                                Staff
                            ' or . = '
                                Pilih Jabatan
                                Komisaris
                                Direktur
                                Staff
                            ')]</value>
      <webElementGuid>59d412c5-57f6-48ec-85f1-46f85cda9908</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
