<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HOT</name>
   <tag></tag>
   <elementGuidId>c6932c99-b836-4dfc-8c75-c6d9b5ca69e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content_container']/div[2]/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f7e5f7e-2eaa-4dde-ad6c-36314ad3315a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://frontliner.intermediatech.id/layanan/assignment_index?type=hot</value>
      <webElementGuid>63b36b27-ba4b-4848-bb16-2c86237ecab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white fw-bold </value>
      <webElementGuid>03952dd5-a38b-4b5c-bf1b-6cc4d86b26a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HOT</value>
      <webElementGuid>27d67623-103e-4b8f-acbc-3c87b5dc950d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content_container&quot;)/div[@class=&quot;row gy-5 g-xl-8&quot;]/div[@class=&quot;col bg-danger px-6 py-8 rounded-2 me-3 mb-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-7&quot;]/a[@class=&quot;text-white fw-bold&quot;]</value>
      <webElementGuid>e9737513-92ba-4382-8150-1176fce4143a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content_container']/div[2]/div[2]/div/div/a</value>
      <webElementGuid>4a766fef-0177-47ae-ba3a-aab4c28ee5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'HOT')]</value>
      <webElementGuid>708b6ef2-68eb-46a5-b4d6-0a428cc763df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment'])[2]/following::a[1]</value>
      <webElementGuid>022a7d21-37e3-48c5-aaee-9f51be48633c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing'])[2]/following::a[2]</value>
      <webElementGuid>4eb2d31a-f205-408d-a4a8-661dac494e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warm'])[1]/preceding::a[1]</value>
      <webElementGuid>38f954fd-049c-4f14-beeb-3f64ef4cbb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cold'])[1]/preceding::a[2]</value>
      <webElementGuid>3a30e585-8bc8-449e-a6a3-0b403812ea57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HOT']/parent::*</value>
      <webElementGuid>ee9308d4-61e6-49ff-95b6-f94944eea351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://frontliner.intermediatech.id/layanan/assignment_index?type=hot')]</value>
      <webElementGuid>a51125bf-0243-44ab-98cc-80e5a4e59279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div/a</value>
      <webElementGuid>39a21760-1c7e-4d1a-979e-cd37c87944c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://frontliner.intermediatech.id/layanan/assignment_index?type=hot' and (text() = 'HOT' or . = 'HOT')]</value>
      <webElementGuid>5cb16b8e-f6b5-4d1d-bb58-83dcdde214a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
