<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select option</name>
   <tag></tag>
   <elementGuidId>ddd2d73a-7765-4c59-9272-4fb9945acae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-sumber_data-ab-container > span.select2-selection__placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-sumber_data-ab-container']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8f1071ff-237b-44c1-a03d-3efd9c289e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__placeholder</value>
      <webElementGuid>9480609a-1fb0-45a6-89fe-e1b84ed506ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select option</value>
      <webElementGuid>d22d6741-d79e-419e-b3cf-d9122fc04c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-sumber_data-ab-container&quot;)/span[@class=&quot;select2-selection__placeholder&quot;]</value>
      <webElementGuid>b0198d6e-de28-4b3d-9b75-8776dc1e098a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-sumber_data-ab-container']/span</value>
      <webElementGuid>492221be-ed7c-4b79-a10a-355073aac01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih'])[2]/following::span[5]</value>
      <webElementGuid>aadaa0d6-74cc-4d7d-b945-534b905d87ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select option'])[1]/following::span[7]</value>
      <webElementGuid>01f640e9-e102-49a3-9e5b-5b6413e3ea7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih'])[3]/preceding::span[3]</value>
      <webElementGuid>9c6efd24-e41c-4c4f-8a0d-b6039e0ccd3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select option'])[3]/preceding::span[3]</value>
      <webElementGuid>d8c8cf2e-f6f0-4f98-906c-608186244959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span/span/span</value>
      <webElementGuid>01febdcf-0990-4d73-99da-b394aa937eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select option' or . = 'Select option')]</value>
      <webElementGuid>c45f46e2-ab9a-4b0b-b675-b17128552c57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
