<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>291da3f2-fd6f-4ce8-bdf0-a7aaafdc5690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='kt_table_users']/tbody/tr/td[9]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.menu-link.px-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f2f894b-94f1-48b9-8d74-04b09452e417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://frontliner.intermediatech.id/layanan/assignment_edit/49</value>
      <webElementGuid>4bb6eb9a-ce2d-45be-8a0d-1036d09d23b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link px-3</value>
      <webElementGuid>5b2232e9-0482-4960-819c-a812cce1673e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kt-users-table-filter</name>
      <type>Main</type>
      <value>edit_row</value>
      <webElementGuid>6f268fe3-fd22-40ed-b226-90e0930cd64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>e7493244-f21f-43ca-8b38-61a8edf25bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_table_users&quot;)/tbody[@class=&quot;text-gray-600 fw-bold&quot;]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-end&quot;]/div[@class=&quot;menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4 show&quot;]/div[@class=&quot;menu-item px-3&quot;]/a[@class=&quot;menu-link px-3&quot;]</value>
      <webElementGuid>6156e070-9f6c-4bcd-a0bd-b622d9b8718a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kt_table_users']/tbody/tr/td[9]/div/div/a</value>
      <webElementGuid>b43bbdd4-b516-4858-a046-37afa59d09de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>7db80413-716a-4f1f-851b-16e958488205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created at 9:12 PM 10/19/2022'])[1]/following::a[2]</value>
      <webElementGuid>87b60d30-de13-40cd-844c-1833cdc3b39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hot'])[1]/following::a[2]</value>
      <webElementGuid>76373ad9-cbb1-4b4e-bd17-347ece8a487d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1]/preceding::a[1]</value>
      <webElementGuid>818b117a-98d3-4a62-abfb-b2e7ec03bd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::a[2]</value>
      <webElementGuid>ec6d9e74-618a-4cac-a589-6619dbbe871f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>62e4c206-2804-462b-b02b-65ee844ee49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://frontliner.intermediatech.id/layanan/assignment_edit/49')]</value>
      <webElementGuid>891cf867-bae5-4d92-8d4e-5f0255dea5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/div/a</value>
      <webElementGuid>5fb40d7e-e646-488f-bad3-a959980176b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://frontliner.intermediatech.id/layanan/assignment_edit/49' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>b9f7bca0-19ca-4cf8-a95a-35e5feb02aff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
