<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>9e9f36f2-6014-4cad-b74d-7066edb3aab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_table_users_wrapper']/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-12.col-md-7.d-flex.align-items-center.justify-content-center.justify-content-md-end</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>530998ba-d28e-469a-a384-a98867107f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end</value>
      <webElementGuid>3bd6bd50-65f2-4cbf-ae6a-fc67e431b69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>53e8c488-4fc0-453b-a76e-b0b47f08d356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_table_users_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end&quot;]</value>
      <webElementGuid>42dc116c-7af5-48c3-854d-7396d6d8b8c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_table_users_wrapper']/div[2]/div[2]</value>
      <webElementGuid>31b81a30-0315-4f55-98db-c2766d828fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[4]/following::div[4]</value>
      <webElementGuid>8dec1985-fd03-49c3-9385-ede4cb41a1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[4]/following::div[5]</value>
      <webElementGuid>55105c6f-1e3a-4ac8-afbc-3bcabb8a13cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intermedia Technology Corporation'])[1]/preceding::div[2]</value>
      <webElementGuid>a3bc898c-aec2-403d-94b6-bc1ddb1fc589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>54944710-8694-4024-b03c-4f19b977b9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1' or . = '1')]</value>
      <webElementGuid>7f07755b-1d46-4b9e-8363-a88cc38cd21d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
