<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Luluk Mufida -                        _016d2b</name>
   <tag></tag>
   <elementGuidId>c6c85497-86c0-4d58-b777-13336be6443d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-marketing_id-rs-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-marketing_id-rs-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2a9f20db-2c87-4c30-94b9-a4f32c0591ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>b8bde0fd-82f9-4691-a672-cbfdffd4fd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-marketing_id-rs-container</value>
      <webElementGuid>f852238f-2402-44bd-b361-a85897658ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>40b3f7c5-e198-4a00-85b5-8c33c77d5222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d072ba3-9d36-400b-910f-78fdb4a20323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Luluk Mufida -
                                            funding</value>
      <webElementGuid>b29788d9-5752-40c1-9375-b0a363434cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Luluk Mufida -
                                            funding</value>
      <webElementGuid>a248c323-c981-4f6c-937b-b2578cb051af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-marketing_id-rs-container&quot;)</value>
      <webElementGuid>4cd11164-5cbc-488f-81f9-4002d82df045</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-marketing_id-rs-container']</value>
      <webElementGuid>68a20595-49cb-4752-bd37-89c4c6517593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div/form/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>a25e59da-6747-442b-9046-99de056677ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing'])[1]/following::span[4]</value>
      <webElementGuid>8763694c-3742-4e09-a961-cff9c5344d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nasabah'])[1]/preceding::span[3]</value>
      <webElementGuid>737ebc44-4dec-43bc-8b12-7d7c62712285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>8663343e-cb90-4c69-88f3-b9646d1c014e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-marketing_id-rs-container' and @title = 'Luluk Mufida -
                                            funding' and (text() = 'Luluk Mufida -
                                            funding' or . = 'Luluk Mufida -
                                            funding')]</value>
      <webElementGuid>86340449-aae5-464b-ae96-de8c54fd4324</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
