<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Marketing Pembiayaan -                _9d6040_1</name>
   <tag></tag>
   <elementGuidId>01207fca-0a38-4774-90b6-5ea0045e25a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-marketing_id-va-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-marketing_id-va-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f16625c5-2f45-40f8-b8ce-d1f04299c81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>c911baf5-1221-4184-9c0c-670639e15da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-marketing_id-va-container</value>
      <webElementGuid>2cd8438c-a9cc-444c-bac8-96deebccc625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>30684bbf-1dc6-4d2c-abc3-ae4ed9e1aede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c55805ba-c0c5-43ee-9207-f58e614c5912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marketing Pembiayaan -
                                            financing</value>
      <webElementGuid>787b4238-0e09-4242-af96-e9d037a2adfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marketing Pembiayaan -
                                            financing</value>
      <webElementGuid>1e6c579c-b0a6-404b-be0c-4b338ccf2afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-marketing_id-va-container&quot;)</value>
      <webElementGuid>0ec0e091-49e0-42f3-b365-8008d85b8b61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-marketing_id-va-container']</value>
      <webElementGuid>101c72a0-49f4-4056-8821-f7c5dc072b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div/form/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>cec7488c-c5b2-4ef6-9d9b-b9dc9db9c433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing'])[1]/following::span[4]</value>
      <webElementGuid>02a5fa62-0bea-4975-963c-cec6c57be47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nasabah'])[1]/preceding::span[3]</value>
      <webElementGuid>47ec389e-8553-4b4d-aea3-d030757fd6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>abd2f9ec-2c0a-4fd2-b5de-9cfc33e0bceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-marketing_id-va-container' and @title = 'Marketing Pembiayaan -
                                            financing' and (text() = 'Marketing Pembiayaan -
                                            financing' or . = 'Marketing Pembiayaan -
                                            financing')]</value>
      <webElementGuid>d2697a94-7c58-45c3-8c61-651e2f68122e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
