<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_bi bi-eye-slash fs-2</name>
   <tag></tag>
   <elementGuidId>ecfd68d1-9fcd-4b28-81d2-d84895977c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-eye-slash.fs-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='kt_body']/div/div/div/div/div/form/div[3]/div/div/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>09dbb82d-4656-48d2-b43b-62f4e3f4b48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-eye-slash fs-2</value>
      <webElementGuid>3121737a-c1d9-4709-9349-696b40fc4464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/div[@class=&quot;d-flex flex-column flex-root&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row flex-column-fluid&quot;]/div[@class=&quot;d-flex flex-column flex-lg-row-auto w-xl-600px positon-xl-relative&quot;]/div[@class=&quot;d-flex flex-center flex-column flex-column-fluid&quot;]/div[@class=&quot;w-lg-600px p-10 p-lg-15 mx-auto&quot;]/form[@class=&quot;form w-100&quot;]/div[@class=&quot;mb-10 fv-row&quot;]/div[@class=&quot;mb-1&quot;]/div[@class=&quot;position-relative mb-3&quot;]/span[@class=&quot;btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2&quot;]/i[@class=&quot;bi bi-eye-slash fs-2&quot;]</value>
      <webElementGuid>8b062fe0-d8c8-4c6a-9944-5add50fee1c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/div/div/div/div/div/form/div[3]/div/div/span/i</value>
      <webElementGuid>4f77f33a-4b61-4385-bc4e-5debdb13a0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>599286b5-1f17-425c-9c8f-7238c99a030f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
