<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Edit Foto_bi bi-pencil-fill fs-7</name>
   <tag></tag>
   <elementGuidId>e60c221a-286d-4292-8586-a130058ab5b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-pencil-fill.fs-7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_contacts_main']/div[2]/form/div/div/div/label/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>189c354b-4e4a-480d-9fe1-43d50bd85650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-pencil-fill fs-7</value>
      <webElementGuid>ed3e5ad0-c105-4ab5-9815-d5cbf6fdf8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_contacts_main&quot;)/div[@class=&quot;card-body pt-5&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mb-7&quot;]/div[@class=&quot;mt-1&quot;]/div[@class=&quot;image-input image-input-outline&quot;]/label[@class=&quot;btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow&quot;]/i[@class=&quot;bi bi-pencil-fill fs-7&quot;]</value>
      <webElementGuid>60ac39c6-751d-4bb4-8eec-75b07a488d50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div[2]/form/div/div/div/label/i</value>
      <webElementGuid>84118ce3-91b0-4d3d-b7eb-9784d94eeef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label/i</value>
      <webElementGuid>4c79d7f7-6eb7-4ac6-ba2e-1e2e80ad83b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
