<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Perusahaan_company_name</name>
   <tag></tag>
   <elementGuidId>7153a7ec-3998-477f-b57e-e86ea4ae63c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#perusahaan_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='perusahaan_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b4f6545-85a2-4929-959b-1baa80fc52bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>perusahaan_value</value>
      <webElementGuid>d0011387-8f72-4591-9be6-4a78744c2010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e30445f-895a-418c-b6f2-fb802e388ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Perusahaan Anda</value>
      <webElementGuid>56bbf91c-e83c-4229-a9b3-dcc13ea06533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid</value>
      <webElementGuid>da3f4c60-be68-4deb-a42b-39546614b576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_name</value>
      <webElementGuid>4192eeca-f82c-4626-8b76-cb52b324c761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>regaksa kaca</value>
      <webElementGuid>c0f1d2dc-c8c3-44bc-bf4b-2760ceba9d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;perusahaan_value&quot;)</value>
      <webElementGuid>80282758-4694-4853-a85a-89cac9ae56b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='perusahaan_value']</value>
      <webElementGuid>d6d979ee-9e12-48ce-8e86-2e14ee1a4407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='perusahaan']/div[2]/input</value>
      <webElementGuid>544d1f97-4587-49ed-a104-7fe335a6e17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/input</value>
      <webElementGuid>c3a9c3a8-ca46-490b-ae81-0e6e734bc265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'perusahaan_value' and @type = 'text' and @placeholder = 'Masukkan Nama Perusahaan Anda' and @name = 'company_name']</value>
      <webElementGuid>9ec0c97d-1b59-4f8c-a564-8c49d84920ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
