<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kategori_potential_category</name>
   <tag></tag>
   <elementGuidId>98913212-f935-4f60-a519-d180ff15817e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category_product_count_yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category_product_count_yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e54ff1fd-6d3a-4133-b4b3-b92984f015b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>7772531a-b927-434f-831e-66d2ad7e9c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>344d097b-deb0-4fbb-950f-efbb43aec0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>pembiayaan</value>
      <webElementGuid>0267bc08-8238-40e8-b098-500ac8e21ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>potential_category</value>
      <webElementGuid>f4d225ea-513a-42a3-b2a0-949fc15db1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category_product_count_yes</value>
      <webElementGuid>6731e946-5f13-43be-be93-dd4cdcfde625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/div[@class=&quot;col-xl-12&quot;]/div[@id=&quot;kt_contacts_main&quot;]/div[@class=&quot;card-body pt-12&quot;]/div[@class=&quot;row fv-row mb-7&quot;]/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;d-flex mt-4&quot;]/div[@class=&quot;form-check form-check-custom form-check-solid me-5&quot;]/input[@id=&quot;category_product_count_yes&quot;]</value>
      <webElementGuid>c6ba7a04-1243-49c4-99a3-7ea392e0ebae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category_product_count_yes']</value>
      <webElementGuid>1203dd51-7ccf-4a64-b8ae-a992025a26d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>4e30167f-c894-4fb4-98e8-42ed70bfd3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>8b2a0835-2547-4c8b-bbf1-20ce5b654864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'potential_category' and @id = 'category_product_count_yes']</value>
      <webElementGuid>1e04fe9d-6b17-4a27-9dd1-ec67b65645eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
