<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Nasabah</name>
   <tag></tag>
   <elementGuidId>f7d569ab-20e5-47b6-85f3-d577e8a28b81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-customer_id-0e-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-customer_id-0e-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c2308814-b1ed-4167-8385-6eccd685fc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>b5d260b8-72c4-4790-b3ca-c86a82cc99bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-customer_id-0e-container</value>
      <webElementGuid>41a7fe1c-8a13-4d6a-926e-3f1969f12866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>93f4652d-23e9-45c5-847f-bbc906a465d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>037be36a-d02a-4ae2-9002-8aac942b2f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pilih Nasabah</value>
      <webElementGuid>59a0a4c0-76d6-40c2-9019-b913e06789d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Nasabah</value>
      <webElementGuid>f2505841-d0d3-41ee-94e2-e36fe12deb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-customer_id-0e-container&quot;)</value>
      <webElementGuid>41ad807a-81b2-40ca-9b47-318ac4f0fbbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-customer_id-0e-container']</value>
      <webElementGuid>69c319ab-58a5-4b2b-8bb8-ed87bbcbcbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div/form/div[2]/div[2]/div/span/span/span/span</value>
      <webElementGuid>e04239b5-902d-4b33-aa2e-75356ad92344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nasabah'])[1]/following::span[4]</value>
      <webElementGuid>4a125386-9724-4ca5-8364-f7a47f8eca24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::span[3]</value>
      <webElementGuid>cbc54029-2573-418b-8f0c-553c5f57ae2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please wait...'])[1]/preceding::span[4]</value>
      <webElementGuid>d0b6299f-1880-4aee-bdbc-072c7705cf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span/span/span/span</value>
      <webElementGuid>c90c6cf2-c966-4401-a62d-4f18ab206b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-customer_id-0e-container' and @title = 'Pilih Nasabah' and (text() = 'Pilih Nasabah' or . = 'Pilih Nasabah')]</value>
      <webElementGuid>461f8f66-b1f0-4f04-8979-8111dd12f0af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
