<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Perusahaan_company_name</name>
   <tag></tag>
   <elementGuidId>20e9c781-f636-4bc4-b514-cf4ffc3ccfd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#perusahaan_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='perusahaan_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb8c1f57-7f55-4833-bb09-5edf74180d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>865a5a68-ac10-4090-a4b0-b9d969117caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>perusahaan_value</value>
      <webElementGuid>1443d8a4-9199-4c47-bcc5-48e4d96ca696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11b6c4bf-aa9f-401b-b20a-6a0faf308c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Perusahaan Anda</value>
      <webElementGuid>c5209c3a-2203-411b-8376-7568b2386eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid</value>
      <webElementGuid>0e713605-8b9d-458d-b597-1a908c10fd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_name</value>
      <webElementGuid>93455d90-23f0-426f-8fdd-4a90e2668a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;perusahaan_value&quot;)</value>
      <webElementGuid>a399c6e3-160d-4c81-a511-7be87edf6e22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='perusahaan_value']</value>
      <webElementGuid>f8ab36b6-d75a-4c51-90b7-728e49a44c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='perusahaan']/div[2]/input</value>
      <webElementGuid>b0867224-006c-435f-b896-9b554752b5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/input</value>
      <webElementGuid>c988cad3-a81e-45e1-9dc8-ae75165fc608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'perusahaan_value' and @type = 'text' and @placeholder = 'Masukkan Nama Perusahaan Anda' and @name = 'company_name']</value>
      <webElementGuid>9ac677bc-4bb3-4d1b-9bd4-69a6d2a76706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
