<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kategori_potential_category</name>
   <tag></tag>
   <elementGuidId>c28d4c77-f55f-4971-8a51-e16b2f67445d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category_product_count_yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category_product_count_yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8326b10-4887-4aa1-85e9-4b03310d4a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>8d89bcd5-dc95-4474-9ed0-c215e3cc5e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e6ba100f-c584-402a-904a-614c989a3a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>pembiayaan</value>
      <webElementGuid>39d2f068-f25d-41f7-b70e-cf67aa67db95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>potential_category</value>
      <webElementGuid>ac37fa1c-fa74-4f7f-a8e8-788c6fb6a3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category_product_count_yes</value>
      <webElementGuid>cf8f6183-9592-431c-a445-2b584c2d567a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/div[@class=&quot;col-xl-12&quot;]/div[@id=&quot;kt_contacts_main&quot;]/div[@class=&quot;card-body pt-7&quot;]/div[@class=&quot;row fv-row mb-7&quot;]/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;d-flex mt-1&quot;]/div[@class=&quot;form-check form-check-custom form-check-solid me-5&quot;]/input[@id=&quot;category_product_count_yes&quot;]</value>
      <webElementGuid>ab53c2bf-bcfe-42dc-a732-67501d31bd66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category_product_count_yes']</value>
      <webElementGuid>140aa1ec-7a0b-431d-b836-269ab40daecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_contacts_main']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>e2249c07-c39b-4647-b370-32fc27a539fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>77a353b0-017b-4751-b981-0675e8833638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'potential_category' and @id = 'category_product_count_yes']</value>
      <webElementGuid>629c80e0-7a75-4c1a-8518-efccd4aad684</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
