<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e0f36b38-9533-490e-a615-2725f3616276</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;user&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_header_user_menu_toggle']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>24ce3623-421d-4c1a-9700-ebf1e970c33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://frontliner.intermediatech.id/admin/image/profile/admin/1679472263-photo-admin.jpg</value>
      <webElementGuid>7fbd329e-b0a0-4241-a5f3-87c37c6e3a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>user</value>
      <webElementGuid>e65be239-dfaf-4614-aa5b-0e1f29ae393d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_header_user_menu_toggle&quot;)/div[@class=&quot;cursor-pointer symbol symbol-30px symbol-md-40px&quot;]/img[1]</value>
      <webElementGuid>812c7b90-a8df-4565-868a-e9e1165f9e37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_header_user_menu_toggle']/div/img</value>
      <webElementGuid>a5d0076a-6173-4275-840f-d2e1996fccba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='user']</value>
      <webElementGuid>26764f4a-a1d3-486d-9e18-fbffdf61e82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>b86b10f4-c2d2-4b6e-99ad-6ebee27c9dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://frontliner.intermediatech.id/admin/image/profile/admin/1679472263-photo-admin.jpg' and @alt = 'user']</value>
      <webElementGuid>385a062d-86fb-4341-9215-aabb8caaf189</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
