<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>794457ca-0a21-40b3-a0f0-534e112d8b8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;user&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_header_user_menu_toggle']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6a9a13c4-d11c-441b-b6ed-bc02a665117b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://frontliner.intermediatech.id/admin/image/profile/manager/835661565-photo-manager.jpg</value>
      <webElementGuid>b0bc7250-2a36-46d4-be09-1a59690f8e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>user</value>
      <webElementGuid>e3c765ac-d84e-41bb-98fb-4b72c3a2d84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_header_user_menu_toggle&quot;)/div[@class=&quot;cursor-pointer symbol symbol-30px symbol-md-40px&quot;]/img[1]</value>
      <webElementGuid>8a412e1b-0e93-4978-bcfe-2fa722a375a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_header_user_menu_toggle']/div/img</value>
      <webElementGuid>bd7b1b94-8107-48a5-b9d0-90add9aab943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='user']</value>
      <webElementGuid>e19a6cbf-a2ef-40bf-b6bb-d7efd6189924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>8ebb1b4a-1e53-46c1-9871-ecf665873991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://frontliner.intermediatech.id/admin/image/profile/manager/835661565-photo-manager.jpg' and @alt = 'user']</value>
      <webElementGuid>5a45e67f-c894-4a7d-b4c5-0126f9bde53d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
