<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Data</name>
   <tag></tag>
   <elementGuidId>a9ebef21-d04a-4c95-a025-567299917ad8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='#kt_aside_menu']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.menu-content.pt-8.pb-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4d92b6c-be57-41f5-b981-81b98167f3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-content pt-8 pb-0</value>
      <webElementGuid>84123b01-c802-4766-b14d-e55aad7c3a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Data
									</value>
      <webElementGuid>f5e321ec-8a39-4e73-9a13-5f1f4dc33820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#kt_aside_menu&quot;)/div[@class=&quot;menu-item&quot;]/div[@class=&quot;menu-content pt-8 pb-0&quot;]</value>
      <webElementGuid>c06a4ca8-cc18-4c8a-90d5-bb1619863269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='#kt_aside_menu']/div[2]/div</value>
      <webElementGuid>744251e0-5dae-47af-ae4e-fe089e81e07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[2]</value>
      <webElementGuid>a8f79a2a-329f-4bb5-ad8a-effcf14b635b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::div[11]</value>
      <webElementGuid>fdbe755e-aec0-4f94-8775-2a7f3ba7f388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment'])[2]/preceding::div[1]</value>
      <webElementGuid>eff94d99-a7c0-4cd4-81a1-c8287c091b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>59d63b0f-d3a4-493a-a723-ece4e089b229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
										Data
									' or . = '
										Data
									')]</value>
      <webElementGuid>007f0c8e-07b6-4e95-a3b4-8feb18022ade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
