<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_102550100</name>
   <tag></tag>
   <elementGuidId>ab1a2a05-329c-4ed0-89ea-f4f6c8ee5f8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='kt_table_users_length']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;kt_table_users_length&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>60f203da-1226-453d-a525-b994b56cd98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kt_table_users_length</value>
      <webElementGuid>5f0b7358-65fc-413f-bd46-8d7b89917135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>kt_table_users</value>
      <webElementGuid>c08f0ee3-12f4-435d-88e9-8873704a4a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-select-sm form-select-solid</value>
      <webElementGuid>6c34169c-6714-43de-a9d6-d651d0b2893c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>102550100</value>
      <webElementGuid>97f9711c-10b3-4cbc-b80f-b98b1afb21ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_table_users_length&quot;)/label[1]/select[@class=&quot;form-select form-select-sm form-select-solid&quot;]</value>
      <webElementGuid>c6601f00-833d-4e54-878d-798eb9f8c992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='kt_table_users_length']</value>
      <webElementGuid>6647b7a7-b19c-40fc-8243-9f6a58322975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_table_users_length']/label/select</value>
      <webElementGuid>76e42312-b1c5-42b2-a61f-4b6cc6f30b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[4]/following::select[1]</value>
      <webElementGuid>551ad56c-e529-40c6-8758-24ed6708fc41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[4]/following::select[1]</value>
      <webElementGuid>0fe596ae-3241-4ebc-af2b-44c8a44c67f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intermedia Technology Corporation'])[1]/preceding::select[1]</value>
      <webElementGuid>2befa493-3514-4f66-8827-450fcc2855d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/select</value>
      <webElementGuid>da21167f-a80f-4eb3-bd3e-b37b7eb5110a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'kt_table_users_length' and (text() = '102550100' or . = '102550100')]</value>
      <webElementGuid>7c347f58-775f-4100-931b-1af6448dbcfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
