<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail_1</name>
   <tag></tag>
   <elementGuidId>30d47e2d-4aa0-4f06-9bcf-6d5683b0d564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='kt_table_users']/tbody/tr[5]/td[9]/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1c77a15-44c8-4c99-95f4-73217154625d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://frontliner.intermediatech.id/layanan/assignment_detail_riwayat/105</value>
      <webElementGuid>23e46257-b6e4-4aaf-8125-d92f25f9048e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link px-3</value>
      <webElementGuid>7c7919de-5092-46be-b383-224a40e5e4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>600a8636-1940-4d82-b2d5-7574e24a5cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_table_users&quot;)/tbody[@class=&quot;text-gray-600 fw-bold&quot;]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-end&quot;]/div[@class=&quot;menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4 show&quot;]/div[@class=&quot;menu-item px-3&quot;]/a[@class=&quot;menu-link px-3&quot;]</value>
      <webElementGuid>c9a6e5ff-55ee-4480-8d2d-1f8e07ccbe17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kt_table_users']/tbody/tr[5]/td[9]/div/div[2]/a</value>
      <webElementGuid>58a989e3-656b-45d8-b889-4eaea9d64f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Detail')])[5]</value>
      <webElementGuid>67ae90c9-104f-49ec-8ae8-aa3939ac987f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[5]/following::a[1]</value>
      <webElementGuid>3e87ef37-1fce-4f83-a15c-0e1ced79590e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created at 9:24 AM 12/24/2022'])[1]/following::a[3]</value>
      <webElementGuid>bbf88050-6aea-461a-a564-ab233229edf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[5]/preceding::a[1]</value>
      <webElementGuid>6c23f57c-ab76-4867-9d78-b46db95d1a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rose Blake'])[1]/preceding::a[2]</value>
      <webElementGuid>95faa7ab-4c9d-4860-9438-5cf35c703971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://frontliner.intermediatech.id/layanan/assignment_detail_riwayat/105')]</value>
      <webElementGuid>726dc35c-1da7-4609-8899-8f2efe22189e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[9]/div/div[2]/a</value>
      <webElementGuid>ebb1d7cf-bab1-41ab-85ce-efcfd60c5ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://frontliner.intermediatech.id/layanan/assignment_detail_riwayat/105' and (text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>07cebecb-b5bb-470c-830f-a4aae57ff50b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
