<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_jaligmail.com_fa fa-envelope</name>
   <tag></tag>
   <elementGuidId>39a6725f-53b2-4721-8e73-f1d3781bdcba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fa.fa-envelope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content_container']/div/div/table/tbody/tr[5]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a814d4d-ecbc-4aec-8a6e-9dd9eb699c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>contact email</value>
      <webElementGuid>ec8fe330-6554-4cb7-802a-13c7676e9f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-envelope</value>
      <webElementGuid>6cecd25e-cd73-47dd-b260-9085def8e1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:jali@gmail.com</value>
      <webElementGuid>fde718e4-1116-424d-affb-b568ccbbabca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content_container&quot;)/div[@class=&quot;row gy-5 g-xl-12&quot;]/div[@class=&quot;col-lg-6&quot;]/table[@class=&quot;table align-middle table-row-dashed fs-6 gy-5&quot;]/tbody[1]/tr[5]/td[2]/a[@class=&quot;fa fa-envelope&quot;]</value>
      <webElementGuid>21da67ef-de6e-42d9-9db3-f9ba466eb3a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content_container']/div/div/table/tbody/tr[5]/td[2]/a</value>
      <webElementGuid>ed5da350-2eac-4e57-9aa8-ba3b5bc09f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:jali@gmail.com')]</value>
      <webElementGuid>97b95ae9-74bb-4f10-a40a-8542d3bcbc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>8feb57f7-e949-4adb-8e7e-fe5daf561afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'contact email' and @href = 'mailto:jali@gmail.com']</value>
      <webElementGuid>7b5f4ac9-a08c-4f75-b9d7-5235eed153b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
