<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ecdd5b0d-b017-4b23-9e62-5fb123c6b44b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content_container']/div[2]/table/tbody/tr/td/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fe93d509-1f1b-4ae2-bec5-566d38e1da99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://frontliner.intermediatech.id/admin/image/attachment/156845942-attachment-attachment.jpg</value>
      <webElementGuid>3234ebfe-0514-4f6f-a7f4-65ec9dc40b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>ca301c7a-b4e8-4971-88f2-28469d8a0f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content_container&quot;)/div[@class=&quot;col-lg-12&quot;]/table[@class=&quot;table align-middle table-row-dashed fs-6 gy-5&quot;]/tbody[1]/tr[1]/td[1]/a[1]/img[1]</value>
      <webElementGuid>5cf31c85-7d99-4d9f-85dc-b8920a6204ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content_container']/div[2]/table/tbody/tr/td/a/img</value>
      <webElementGuid>7b0fe69b-dcff-49be-a121-80c73538a357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://frontliner.intermediatech.id/admin/image/attachment/156845942-attachment-attachment.jpg')]</value>
      <webElementGuid>bf664050-9178-486b-bd7c-66c784b6eb7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/img</value>
      <webElementGuid>ad839c84-4b72-45d6-90b4-d174346d6ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://frontliner.intermediatech.id/admin/image/attachment/156845942-attachment-attachment.jpg']</value>
      <webElementGuid>eece81fe-3123-4ba1-b959-eeaf6fa79f18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
